---
title: "Task B: Create a dashboard and blog in your website"
author: "Liangliang Zhang, ph.D."
date: last-modified
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment = NA)
```

## Getting Started with Quarto Dashboard

- Please read through the tutorials for Quarto Dashboards https://quarto.org/docs/dashboards/

## Examples of Quarto Dashboard using R coding

- [Dashboard Example 1](dashboard1.qmd), Labor and Delivery Dashboard
- [Dashboard Example 2](dashboard1.qmd), Palmer Penguins

## The Five Key Elements

Dr. Zhang will be happy if your dashboard clearly includes at least the
following five elements:

1.  A front page including a photo of you or of something relevant to
    you.
2.  Links to your social media presence, if any, and a way for people to
    get in touch with you via email.
3.  An About Me or Welcome section on your front page, which briefly
    describes what you’re doing now.
4.  Some information on your Education, Experiences, and/or Projects
5.  A way to download your CV

A blog is also an appealing way to connect your thoughts with the world,
and including non-professional stuff is OK, too, of course.





